const FINAL_QUALIFICATION_QUESTIONS = salesPlaysData.checklist_qualificacao;
const REPORTABLE_MATERIALS = ['account_plan', 'follow_up_email', 'crm_description', 'executive_summary'];
const stageLabels = { situacao: 'Situação', problema: 'Problema', implicacao: 'Implicação', need_payoff: 'Need-Payoff', qualificacao: 'Qualificação', proximo_passo: 'Próximo passo' };
const responseStatusLabels = { respondida: 'Respondida', sem_resposta: 'Marcada sem resposta', nao_soube: 'Cliente não soube responder', nao_se_aplica: 'Não se aplica', responder_depois: 'Responder depois' };
function allSavedResponses(meeting) { return Object.values(meeting?.respostas || {}).filter((response) => response && response.meeting_id); }
function responseDate(response) { return new Date(response.updated_at || response.created_at).toLocaleString('pt-BR'); }
function answersForPlay(meeting, playId) { return allSavedResponses(meeting).filter((response) => response.sales_play_id === playId); }
function primaryPlay(meeting) { const counts = {}; allSavedResponses(meeting).forEach((response) => { counts[response.sales_play_id] = (counts[response.sales_play_id] || 0) + 1; }); return state?.plays?.find((play) => play.id === Number(Object.entries(counts).sort((a, b) => b[1] - a[1])[0]?.[0])) || state.plays.find((play) => play.id === meeting.sales_play_ativo) || state.plays[0]; }
function checklistSummary(meetingId) { const checklist = getFinalChecklist(meetingId); if (!checklist) return 'Não registrado.'; return `${checklist.total_sim}/10 (${checklist.percentual}%)`; }
function gerarInteligenciaEstruturada(meetingId) { const meeting = getMeetingById(meetingId); const responses = allSavedResponses(meeting); const grouped = {}; responses.forEach((response) => { grouped[response.sales_play_id] = (grouped[response.sales_play_id] || 0) + 1; }); const play = primaryPlay(meeting); const products = [...new Set(responses.map((response) => state.plays.find((item) => item.id === response.sales_play_id)?.solucao_potencial).filter(Boolean))]; const stageCounts = {}; responses.forEach((response) => { if (response.etapa_spin !== 'qualificacao' && response.etapa_spin !== 'proximo_passo') stageCounts[response.etapa_spin] = (stageCounts[response.etapa_spin] || 0) + 1; }); const bestStage = Object.entries(stageCounts).sort((a, b) => b[1] - a[1])[0]; return { opening: responses.length && play ? `Tema principal: ${play.titulo}. A investigação está em ${stageLabels[bestStage?.[0]]?.toUpperCase() || 'ANDAMENTO'} com ${responses.length} registro(s) baseado(s) nas respostas da reunião.` : 'Não há respostas suficientes registradas para gerar este conteúdo.', products: products.length ? products : ['Não identificados'], spin: bestStage && play ? `${stageLabels[bestStage[0]]} · ${bestStage[1]} resposta(s)` : 'Não identificado', opportunities: products.length ? [...new Set(responses.map((response) => state.plays.find((item) => item.id === response.sales_play_id)?.titulo).filter(Boolean))] : ['Nenhuma oportunidade identificada com base nas respostas registradas.'], qualification: `Qualificação: ${checklistSummary(meetingId)}` }; }
function gerarTranscricaoCompleta(meetingId) { const meeting = getMeetingById(meetingId); const responses = allSavedResponses(meeting); if (!responses.length) return 'Nenhuma pergunta foi registrada durante esta reunião.'; return state.plays.filter((play) => responses.some((response) => response.sales_play_id === play.id)).map((play) => { const playResponses = responses.filter((response) => response.sales_play_id === play.id); const sections = ['situacao', 'problema', 'implicacao', 'need_payoff', 'qualificacao', 'proximo_passo'].map((stage) => { const items = playResponses.filter((response) => response.etapa_spin === stage); if (!items.length) return ''; return `\n${stageLabels[stage].toUpperCase()}\n${items.map((response) => `P: ${response.pergunta || response.question_uid}\nR: ${response.resposta || '—'}\nStatus: ${responseStatusLabels[response.status] || response.status} · ${responseDate(response)}`).join('\n\n')}`; }).filter(Boolean).join('\n'); return `\n━━ ${play.titulo} ━━${sections}`; }).join('\n'); }
function generatedMaterials(meetingId) { const meeting = getMeetingById(meetingId); const intelligence = gerarInteligenciaEstruturada(meetingId); const responses = allSavedResponses(meeting); const pains = responses.filter((response) => response.etapa_spin === 'problema' || response.etapa_spin === 'implicacao').map((response) => response.resposta).filter(Boolean); const next = Object.values(meeting.proximo_passo_detalhado || {}).filter(Boolean).join('; '); return { account_plan: `Empresa: ${meeting.empresa || 'Não informado'} | TPID: ${meeting.tpid || 'Não informado'} | Segmento: ${meeting.segmento || 'Não informado'}\nDores e necessidades registradas: ${pains.join(' | ') || 'Não há respostas suficientes registradas para gerar este conteúdo.'}\nOportunidades: ${intelligence.opportunities.join(', ')}\nPróximos passos: ${next || meeting.proximo_passo || 'Não informado.'}`, follow_up_email: `Assunto: Próximos passos — ${meeting.assunto}\n\nOlá, ${meeting.cliente}.\n\nObrigado pela conversa sobre ${meeting.assunto}. Registramos os seguintes próximos passos: ${next || meeting.proximo_passo || 'Não há próximo passo registrado.'}\n\nAtenciosamente,\n${USER_NAME}`, crm_description: intelligence.products[0] === 'Não identificados' ? 'Não há solução identificada com base nas respostas registradas.' : `Oportunidade ${intelligence.products.join(', ')}.`, executive_summary: responses.length ? `Discussão sobre ${meeting.assunto}. O tema principal foi ${primaryPlay(meeting)?.titulo || 'não identificado'}, com ${responses.length} resposta(s) registrada(s).` : 'Não há respostas suficientes registradas para gerar este conteúdo.' }; }
function getReportMaterials(meetingId) { const saved = getReportMaterial(meetingId); const generated = generatedMaterials(meetingId); return REPORTABLE_MATERIALS.reduce((result, key) => { result[key] = saved[key] || generated[key]; return result; }, {}); }
function auditHtml(meetingId) { return getAudit(meetingId).slice().reverse().map((event) => `<li><time>${new Date(event.data_hora).toLocaleString('pt-BR')}</time><span>${escapeHtml(event.descricao)}</span></li>`).join('') || '<li>Nenhum evento registrado.</li>'; }
function escapeHtml(value) { return String(value || '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' })[character]); }
