const VISUAL_LIBRARY_ITEMS = [
  { id: 'licenses', number: '01', title: 'M365 Business x Enterprise', subtitle: 'Comparativo de licenças', render: renderM365LicenseComparison },
  { id: 'e3-e5', number: '02', title: 'Microsoft 365 E3 x E5', subtitle: 'Evolução de segurança e conformidade', render: renderE3E5 },
  { id: 'security', number: '03', title: 'Mapa de Segurança Microsoft', subtitle: 'Solução por domínio', render: renderSecurityMap },
  { id: 'copilot', number: '04', title: 'Mapa Copilot', subtitle: 'Chat, Microsoft 365 e agentes', render: renderCopilotMap },
  { id: 'when-to-sell', number: '05', title: 'Quando vender cada produto', subtitle: 'Sinal do cliente e solução', render: renderWhenToSell },
  { id: 'zero-trust', number: '06', title: 'Arquitetura Zero Trust', subtitle: 'Princípios e pilares', render: renderZeroTrust },
  { id: 'copilot-adoption', number: '07', title: 'Jornada de adoção Copilot', subtitle: 'Do preparo à expansão', render: renderCopilotAdoption },
  { id: 'power-platform', number: '08', title: 'Matriz Power Platform', subtitle: 'Produto por necessidade', render: renderPowerPlatform }
];

const licenseRows = [
  ['Email Exchange', '✅', '✅', '✅', '✅', '✅'], ['Teams', '✅', '✅', '✅', '✅', '✅'], ['Desktop Apps', '❌', '✅', '✅', '✅', '✅'], ['Intune', '❌', '❌', '✅', '✅', '✅'], ['Defender for Business', '❌', '❌', '✅', '❌', '❌'], ['Defender for Endpoint', '❌', '❌', '❌', '✅', '✅'], ['Defender for Office', '❌', '❌', '❌', 'Add-on', '✅'], ['Entra ID P1', '❌', '❌', '✅', '✅', '✅'], ['Entra ID P2', '❌', '❌', '❌', '❌', '✅'], ['Purview', '❌', '❌', '❌', 'Básico', 'Avançado'], ['Copilot elegível', '✅', '✅', '✅', '✅', '✅']
];
function visualTable(headers, rows) { return `<div class="visual-table-wrap"><table class="visual-table"><thead><tr>${headers.map((header) => `<th>${header}</th>`).join('')}</tr></thead><tbody>${rows.map((row) => `<tr>${row.map((cell, index) => `<${index ? 'td' : 'th'}>${cell}</${index ? 'td' : 'th'}>`).join('')}</tr>`).join('')}</tbody></table></div>`; }
function renderM365LicenseComparison() { return `<div class="visual-content-intro"><span>Comparativo rápido</span><h3>Microsoft 365 License Comparison</h3><p>Use os filtros visuais para identificar a distância entre a necessidade atual e a oferta recomendada.</p></div>${visualTable(['Recurso', 'Business Basic', 'Business Standard', 'Business Premium', 'M365 E3', 'M365 E5'], licenseRows)}`; }
function renderE3E5() { return `<div class="visual-content-intro"><span>Enterprise</span><h3>E3 x E5</h3><p>O E5 amplia os recursos avançados de identidade, proteção, conformidade e análise.</p></div>${visualTable(['Capacidade', 'M365 E3', 'M365 E5', 'Conversa comercial'], [['Identidade', 'Entra ID P1', 'Entra ID P2', 'Acesso adaptativo e proteção avançada'], ['Proteção de endpoint', 'Defender for Endpoint', 'Defender for Endpoint', 'Ampliar visibilidade e resposta'], ['Proteção de e-mail', 'Add-on', 'Incluído', 'Reduzir risco de phishing'], ['Purview', 'Básico', 'Avançado', 'Governança, risco e conformidade'], ['Copilot elegível', 'Sim', 'Sim', 'Avaliar requisitos e licenciamento atual']])}`; }
function renderSecurityMap() { const items = [['Identidade', 'Microsoft Entra', '◈'], ['Dispositivos', 'Microsoft Intune', '▣'], ['E-mail e colaboração', 'Defender for Office 365', '✉'], ['Endpoints', 'Defender for Endpoint', '◇'], ['Dados', 'Microsoft Purview', '◆'], ['SIEM / SOC', 'Microsoft Sentinel', '◎'], ['IA para segurança', 'Security Copilot', '✦']]; return `<div class="visual-content-intro"><span>Mapa de soluções</span><h3>Segurança Microsoft</h3><p>Selecione o domínio do problema e conduza a conversa para a solução correspondente.</p></div><div class="security-map">${items.map(([domain, product, icon]) => `<article><b>${icon}</b><span>${domain}</span><strong>${product}</strong></article>`).join('')}</div>`; }
function renderCopilotMap() { return `<div class="visual-content-intro"><span>Inteligência artificial</span><h3>Mapa Copilot</h3><p>Posicione a solução conforme a necessidade de produtividade, contexto corporativo ou automação.</p></div><div class="copilot-map"><article><span>01</span><h4>Copilot Chat</h4><p>Conversas assistidas por IA para produtividade individual.</p></article><article><span>02</span><h4>Microsoft 365 Copilot</h4><p>Experiência integrada aos aplicativos e ao contexto de trabalho autorizado.</p></article><article><span>03</span><h4>Agentes</h4><p>Assistentes especializados com conhecimento, instruções e ações do negócio.</p></article></div>`; }
function renderWhenToSell() { return `<div class="visual-content-intro"><span>Sinais de oportunidade</span><h3>Quando vender cada produto</h3><p>Transforme a fala do cliente em uma próxima pergunta comercial.</p></div>${visualTable(['Cliente fala', 'Produto recomendado'], [['“Preciso controlar notebooks”', 'Microsoft Intune'], ['“Estou sofrendo phishing”', 'Defender for Office 365'], ['“Quero MFA”', 'Microsoft Entra ID'], ['“Preciso proteger servidores”', 'Defender for Servers'], ['“Quero monitorar incidentes”', 'Microsoft Sentinel'], ['“Quero produtividade com IA”', 'Microsoft Copilot'], ['“Quero governança de dados”', 'Microsoft Purview']])}`; }
function renderZeroTrust() { return `<div class="visual-content-intro"><span>Arquitetura</span><h3>Zero Trust Microsoft</h3><p>Três princípios orientam a estratégia em todos os pilares de segurança.</p></div><div class="zero-trust-principles"><article><b>01</b><h4>Verificar explicitamente</h4><p>Validar identidade, dispositivo, localização, risco e contexto.</p></article><article><b>02</b><h4>Usar privilégio mínimo</h4><p>Limitar acesso por tempo, função e necessidade real.</p></article><article><b>03</b><h4>Assumir violação</h4><p>Segmentar, monitorar e reduzir o impacto de incidentes.</p></article></div><div class="zero-trust-pillars"><span>Identidades</span><span>Endpoints</span><span>Aplicativos</span><span>Dados</span><span>Infraestrutura</span><span>Rede</span></div>`; }
function renderCopilotAdoption() { const steps = [['Preparar', 'Definir cenários, segurança e patrocinadores.'], ['Pilotar', 'Selecionar grupos e casos de uso prioritários.'], ['Capacitar', 'Treinar usuários e líderes com exemplos reais.'], ['Medir', 'Acompanhar uso, valor, qualidade e riscos.'], ['Expandir', 'Escalar boas práticas, agentes e novos processos.']]; return `<div class="visual-content-intro"><span>Adoção</span><h3>Jornada de adoção Copilot</h3><p>Uma evolução estruturada reduz riscos e acelera a geração de valor.</p></div><div class="adoption-journey">${steps.map(([title, text], index) => `<article><b>${index + 1}</b><h4>${title}</h4><p>${text}</p></article>`).join('')}</div>`; }
function renderPowerPlatform() { return `<div class="visual-content-intro"><span>Low-code</span><h3>Matriz de licenciamento Power Platform</h3><p>Comece pela necessidade e valide conectores, capacidade, ambiente e direitos de uso.</p></div>${visualTable(['Produto', 'Melhor para', 'Validar antes da proposta'], [['Power Apps', 'Aplicativos e processos internos', 'Usuários, conectores premium e Dataverse'], ['Power Automate', 'Automação e aprovações', 'Tipo de fluxo, execução e conectores'], ['Power BI', 'Análise e visualização', 'Compartilhamento, capacidade e público'], ['Copilot Studio', 'Agentes e automação conversacional', 'Mensagens, canais, ferramentas e consumo']])}`; }

let activeVisualLibraryItem = 'licenses';
function renderVisualLibrary() { const nav = document.getElementById('visualLibraryNav'); const content = document.getElementById('visualLibraryContent'); if (!nav || !content) return; nav.innerHTML = VISUAL_LIBRARY_ITEMS.map((item) => `<button type="button" role="tab" aria-selected="${item.id === activeVisualLibraryItem}" class="${item.id === activeVisualLibraryItem ? 'active' : ''}" data-visual-library="${item.id}"><span>${item.number}</span><strong>${item.title}</strong><small>${item.subtitle}</small></button>`).join(''); const active = VISUAL_LIBRARY_ITEMS.find((item) => item.id === activeVisualLibraryItem); content.innerHTML = active.render(); nav.querySelectorAll('[data-visual-library]').forEach((button) => button.addEventListener('click', () => { activeVisualLibraryItem = button.dataset.visualLibrary; renderVisualLibrary(); content.scrollIntoView({ behavior: 'smooth', block: 'nearest' }); })); }
function initializeVisualLibrary() { const library = document.getElementById('libraryView'); const workspace = library?.querySelector('.library-workspace'); if (!library || !workspace || document.getElementById('visualLibraryNav')) return; const section = document.createElement('section'); section.className = 'visual-library'; section.setAttribute('aria-labelledby', 'visualLibraryTitle'); section.innerHTML = `<div class="visual-library-heading"><div><p class="eyebrow">Referência rápida</p><h2 id="visualLibraryTitle">Biblioteca visual Microsoft</h2><p>Compare ofertas e identifique oportunidades durante a conversa.</p></div><span>Conteúdo interativo</span></div><div id="visualLibraryNav" class="visual-library-nav" role="tablist"></div><article id="visualLibraryContent" class="visual-library-content" aria-live="polite"></article><p class="visual-library-disclaimer">Material de apoio comercial. Confirme licenciamento, disponibilidade regional e condições atuais antes de apresentar uma proposta.</p>`; library.insertBefore(section, workspace); renderVisualLibrary(); }
initializeVisualLibrary();
